spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/order_db_0?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 50
        pool-name: hikari_jdbc_conn_pool
        auto-commit: true
    primary1:
      jdbc-url: jdbc:mysql://localhost:3306/order_db_1?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 50
        pool-name: hikari_jdbc_conn_pool
        auto-commit: true
    replication1:
      jdbc-url: jdbc:mysql://localhost:3316/order_db_0?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 50
        pool-name: hikari_jdbc_conn_pool
        auto-commit: true
    replication-order1:
      jdbc-url: jdbc:mysql://localhost:3316/order_db_1?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 50
        pool-name: hikari_jdbc_conn_pool
        auto-commit: true
#    replication2:
#      jdbc-url: jdbc:mysql://localhost:3326/db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#      username: root
#      password:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        connection-timeout: 20000
#        minimum-idle: 10
#        maximum-pool-size: 50
#        pool-name: hikari_jdbc_conn_pool
#        auto-commit: true

server:
  port: 8803
  servlet:
    context-path: /order
